// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
package sword

import _ "pkg/mod/github.com/!go!admin!group/themes@v0.0.39/sword/packrd"
